name: Deploy to Genesis City

on:
  push:
    branches:
      - release

env:
  DCL_PRIVATE_KEY: ${{ secrets.DCL_PRIVATE_KEY }}

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install decentraland
      run: npm i -g decentraland@latest
    - name: Install npm packages
      run: |
        npm install
    - name: Build scene
      run: |
        npm run build
    - name: Deploy scene
      run: |
         dcl deploy -t linker-server.decentraland.org --skip-validations true